#:schema ./lunchbox.schema.json

[processes.vite]
shell = "mise vite"
autostart = true

[processes.inngest]
shell = "mise inngest"
autostart = true

[processes.dev]
shell = "mise dev"
autostart = true
